apiVersion: v1
data:
  namespaced: {{ .Values.configs.namespacedScope | quote }}
  managed.namespace: {{ .Values.configs.managedNamespace | quote }}
  controller.leader.election.disabled: {{ .Values.controller.configs.leaderElection.disabled | quote }}
  controller.leader.election.lease.duration: {{ .Values.controller.configs.leaderElection.leaseDuration | quote }}
  controller.leader.election.lease.renew.deadline: {{ .Values.controller.configs.leaderElection.renewDuration | quote }}
  controller.leader.election.lease.renew.period: {{ .Values.controller.configs.leaderElection.renewPeriod | quote }}
  server.insecure: {{ .Values.server.configs.insecure | quote }}
  server.port: "{{ include "server.configs.port" . }}"
  server.base.href: {{ .Values.server.configs.baseHref | quote }}
  server.readonly: {{ .Values.server.configs.readOnly | quote }}
  server.disable.auth: {{ .Values.server.configs.authDisable | quote }}
  server.dex.server: {{ .Values.server.configs.dexServer | quote }}
  server.address: "{{ .Values.server.configs.host }}:{{ include "server.configs.port" . }}"
  server.cors.allowed.origins: {{ .Values.server.configs.cors.allowedOrigin | quote }}
  server.daemon.client.protocol: {{ .Values.server.configs.daemon.client.protocol | quote }}
kind: ConfigMap
metadata:
  name: numaflow-cmd-params-config
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}