apiVersion: v1
data:
  config.yaml: |-
    connectors:
      - type: github
        # https://dexidp.io/docs/connectors/github/
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          orgs:
            - name: <ORG_NAME>
              teams:
                - admin
                - readonly
kind: ConfigMap
metadata:
  name: numaflow-dex-server-config
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}