apiVersion: v1
kind: Service
metadata:
  name: numaflow-webhook
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/component: numaflow-webhook
    app.kubernetes.io/name: numaflow-webhook
    app.kubernetes.io/part-of: numaflow