{{- if and (eq .Values.configs.webhook.enabled true) (eq .Values.configs.namespacedScope false) .Values.configs.webhook.podDisruptionBudget.enabled }}
{{- if and (ne .Values.configs.webhook.podDisruptionBudget.minAvailable nil) (ne .Values.configs.webhook.podDisruptionBudget.maxUnavailable nil) }}
{{- fail "configs.webhook.podDisruptionBudget.minAvailable and configs.webhook.podDisruptionBudget.maxUnavailable are mutually exclusive" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: numaflow-webhook
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if ne .Values.configs.webhook.podDisruptionBudget.minAvailable nil }}
  minAvailable: {{ .Values.configs.webhook.podDisruptionBudget.minAvailable }}
  {{- else if ne .Values.configs.webhook.podDisruptionBudget.maxUnavailable nil }}
  maxUnavailable: {{ .Values.configs.webhook.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  {{- fail "configs.webhook.podDisruptionBudget requires minAvailable or maxUnavailable" }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: numaflow-webhook
      app.kubernetes.io/name: numaflow-webhook
      app.kubernetes.io/part-of: numaflow
{{- end }}
