{{- if .Values.controller.podDisruptionBudget.enabled }}
{{- if and (ne .Values.controller.podDisruptionBudget.minAvailable nil) (ne .Values.controller.podDisruptionBudget.maxUnavailable nil) }}
{{- fail "controller.podDisruptionBudget.minAvailable and controller.podDisruptionBudget.maxUnavailable are mutually exclusive" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: numaflow-controller
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if ne .Values.controller.podDisruptionBudget.minAvailable nil }}
  minAvailable: {{ .Values.controller.podDisruptionBudget.minAvailable }}
  {{- else if ne .Values.controller.podDisruptionBudget.maxUnavailable nil }}
  maxUnavailable: {{ .Values.controller.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  {{- fail "controller.podDisruptionBudget requires minAvailable or maxUnavailable" }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/name: controller-manager
      app.kubernetes.io/part-of: numaflow
{{- end }}
