apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-controller
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/name: controller-manager
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/name: controller-manager
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
        - args:
            - controller
          env:
            - name: NUMAFLOW_IMAGE
              value: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
            - name: NUMAFLOW_CONTROLLER_NAMESPACED
              valueFrom:
                configMapKeyRef:
                  key: namespaced
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_CONTROLLER_MANAGED_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: managed.namespace
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_DISABLED
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.disabled
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_LEASE_DURATION
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.lease.duration
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_LEASE_RENEW_DEADLINE
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.lease.renew.deadline
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_LEASE_RENEW_PERIOD
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.lease.renew.period
                  name: numaflow-cmd-params-config
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          name: controller-manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          ports:
            - containerPort: 9090
              name: metrics
          volumeMounts:
            - mountPath: /etc/numaflow
              name: controller-config-volume
      securityContext:
        runAsNonRoot: true
        runAsUser: 9737
      serviceAccountName: numaflow-sa
      volumes:
        - configMap:
            name: numaflow-controller-config
          name: controller-config-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-dex-server
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/name: numaflow-dex-server
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dex-server
        app.kubernetes.io/name: numaflow-dex-server
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
        - command: ["/usr/local/bin/dex", "serve", "/etc/numaflow/dex/cfg/config.yaml"]
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: dex-github-client-id
                  name: numaflow-dex-secrets
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: dex-github-client-secret
                  name: numaflow-dex-secrets
          image: {{ .Values.dexServer.image.repository }}:{{ .Values.dexServer.image.tag }}
          imagePullPolicy: {{ .Values.dexServer.image.pullPolicy }}
          name: dex
          ports:
            - containerPort: 5556
          volumeMounts:
          - mountPath: /etc/numaflow/dex/cfg/config.yaml
            name: generated-dex-config
            subPath: config.yaml
          - mountPath: /etc/numaflow/dex/tls/tls.crt
            name: tls
            subPath: tls.crt
          - mountPath: /etc/numaflow/dex/tls/tls.key
            name: tls
            subPath: tls.key
      initContainers:
        - args:
            - dex-server-init
          env:
            - name: NUMAFLOW_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: server.address
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_BASE_HREF
              valueFrom:
                configMapKeyRef:
                  key: server.base.href
                  name: numaflow-cmd-params-config
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          name: dex-init
          volumeMounts:
            - mountPath: /cfg
              name: connector-config
            - mountPath: /tls
              name: tls
            - mountPath: /tmp
              name: generated-dex-config
      serviceAccountName: numaflow-dex-server
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: numaflow-dex-server-config
          name: connector-config
        - emptyDir: {}
          name: tls
        - emptyDir: {}
          name: generated-dex-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-server
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: numaflow-ux
      app.kubernetes.io/name: numaflow-ux
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: numaflow-ux
        app.kubernetes.io/name: numaflow-ux
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
        - args:
            - server
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMAFLOW_SERVER_INSECURE
              valueFrom:
                configMapKeyRef:
                  key: server.insecure
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_PORT_NUMBER
              valueFrom:
                configMapKeyRef:
                  key: server.port
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_NAMESPACED
              valueFrom:
                configMapKeyRef:
                  key: namespaced
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_MANAGED_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: managed.namespace
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_BASE_HREF
              valueFrom:
                configMapKeyRef:
                  key: server.base.href
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_READONLY
              valueFrom:
                configMapKeyRef:
                  key: server.readonly
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: server.disable.auth
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_DEX_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  key: server.dex.server
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: server.address
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: server.cors.allowed.origins
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_DAEMON_CLIENT_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: numaflow-cmd-params-config
                  key: server.daemon.client.protocol
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          ports:
            - containerPort: {{ include "server.configs.port" . }}
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ include "server.configs.port" . }}
              {{- if .Values.server.configs.insecure }}
              scheme: HTTP
              {{- else }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 3
            periodSeconds: 3
          name: main
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /ui/build/runtime-env.js
              name: env-volume
              subPath: runtime-env.js
            - mountPath: /ui/build/index.html
              name: env-volume
              subPath: index.html
            - mountPath: /etc/numaflow
              name: rbac-config
            - mountPath: /etc/numaflow/metrics-proxy
              name: metrics-proxy-config
      initContainers:
        - args:
            - server-init
          env:
            - name: NUMAFLOW_SERVER_BASE_HREF
              valueFrom:
                configMapKeyRef:
                  key: server.base.href
                  name: numaflow-cmd-params-config
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          name: server-init
          volumeMounts:
            - mountPath: /opt/numaflow
              name: env-volume
        - args:
            - server-secrets-init
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          name: server-secrets-init
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMAFLOW_SERVER_DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: server.disable.auth
                  name: numaflow-cmd-params-config
                  optional: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 9737
      serviceAccountName: numaflow-server-sa
      volumes:
        - emptyDir: {}
          name: env-volume
        - configMap:
            name: numaflow-server-rbac-config
          name: rbac-config
        - configMap:
            name: numaflow-server-metrics-proxy-config
          name: metrics-proxy-config

{{- if and (eq .Values.configs.webhook.enabled true) (eq .Values.configs.namespacedScope false) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-webhook
  labels:
      {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: numaflow-webhook
      app.kubernetes.io/name: numaflow-webhook
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: numaflow-webhook
        app.kubernetes.io/name: numaflow-webhook
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
        - args:
            - webhook-service
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORT
              value: "443"
            - name: DEPLOYMENT_NAME
              value: numaflow-webhook
            - name: SERVICE_NAME
              value: numaflow-webhook
            - name: CLUSTER_ROLE_NAME
              value: numaflow-webhook
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          name: webhook
      serviceAccountName: numaflow-webhook-sa
{{- end }}