{{- range list "numaflow-dex-server" "numaflow-sa" "numaflow-server-sa" "numaflow-webhook-sa" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  labels:
    {{- include "numaflow.labels" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
---
{{ end }}