{{- range list .Values.controller.serviceAccount .Values.dexServer.serviceAccount .Values.server.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  labels:
    {{- include "numaflow.labels" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
---
{{ end }}