apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-server
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: numaflow-ux
      app.kubernetes.io/name: numaflow-ux
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: numaflow-ux
        app.kubernetes.io/name: numaflow-ux
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
        - args:
            - server
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMAFLOW_SERVER_INSECURE
              valueFrom:
                configMapKeyRef:
                  key: server.insecure
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_PORT_NUMBER
              valueFrom:
                configMapKeyRef:
                  key: server.port
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_NAMESPACED
              valueFrom:
                configMapKeyRef:
                  key: namespaced
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_MANAGED_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: managed.namespace
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_BASE_HREF
              valueFrom:
                configMapKeyRef:
                  key: server.base.href
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_READONLY
              valueFrom:
                configMapKeyRef:
                  key: server.readonly
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: server.disable.auth
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_DEX_SERVER_ADDR
              valueFrom:
                configMapKeyRef:
                  key: server.dex.server
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: server.address
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: server.cors.allowed.origins
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_SERVER_DAEMON_CLIENT_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: numaflow-cmd-params-config
                  key: server.daemon.client.protocol
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          ports:
            - containerPort: {{ include "server.configs.port" . }}
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ include "server.configs.port" . }}
              {{- if .Values.server.configs.insecure }}
              scheme: HTTP
              {{- else }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 3
            periodSeconds: 3
          name: main
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /ui/build/runtime-env.js
              name: env-volume
              subPath: runtime-env.js
            - mountPath: /ui/build/index.html
              name: env-volume
              subPath: index.html
            - mountPath: /etc/numaflow
              name: rbac-config
            - mountPath: /etc/numaflow/metrics-proxy
              name: metrics-proxy-config
      initContainers:
        - args:
            - server-init
          env:
            - name: NUMAFLOW_SERVER_BASE_HREF
              valueFrom:
                configMapKeyRef:
                  key: server.base.href
                  name: numaflow-cmd-params-config
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          name: server-init
          volumeMounts:
            - mountPath: /opt/numaflow
              name: env-volume
        - args:
            - server-secrets-init
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          name: server-secrets-init
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMAFLOW_SERVER_DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  key: server.disable.auth
                  name: numaflow-cmd-params-config
                  optional: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 9737
      serviceAccountName: numaflow-server-sa
      volumes:
        - emptyDir: {}
          name: env-volume
        - configMap:
            name: numaflow-server-rbac-config
          name: rbac-config
        - configMap:
            name: numaflow-server-metrics-proxy-config
          name: metrics-proxy-config