apiVersion: apps/v1
kind: Deployment
metadata:
  name: numaflow-controller
  labels:
    {{- include "numaflow.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/name: controller-manager
      app.kubernetes.io/part-of: numaflow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/name: controller-manager
        app.kubernetes.io/part-of: numaflow
    spec:
      containers:
        - args:
            - controller
          env:
            - name: NUMAFLOW_IMAGE
              value: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
            - name: NUMAFLOW_CONTROLLER_NAMESPACED
              valueFrom:
                configMapKeyRef:
                  key: namespaced
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_CONTROLLER_MANAGED_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: managed.namespace
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_DISABLED
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.disabled
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_LEASE_DURATION
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.lease.duration
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_LEASE_RENEW_DEADLINE
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.lease.renew.deadline
                  name: numaflow-cmd-params-config
                  optional: true
            - name: NUMAFLOW_LEADER_ELECTION_LEASE_RENEW_PERIOD
              valueFrom:
                configMapKeyRef:
                  key: controller.leader.election.lease.renew.period
                  name: numaflow-cmd-params-config
                  optional: true
          image: {{ .Values.numaflow.image.repository }}:{{ .Values.numaflow.image.tag }}
          imagePullPolicy: {{ .Values.numaflow.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          name: controller-manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          ports:
            - containerPort: 9090
              name: metrics
          volumeMounts:
            - mountPath: /etc/numaflow
              name: controller-config-volume
      securityContext:
        runAsNonRoot: true
        runAsUser: 9737
      serviceAccountName: numaflow-sa
      volumes:
        - configMap:
            name: numaflow-controller-config
          name: controller-config-volume