{{- if eq .Values.configs.namespacedScope true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: numaflow-role-binding
  labels:
	{{- include "numaflow.labels" . | nindent 4 }}
    app.kubernetes.io/name: numaflow-controller-manager
    app.kubernetes.io/part-of: numaflow
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: numaflow-role
subjects:
  - kind: ServiceAccount
    name: numaflow-sa

{{- end}}